Spring:
  application:
    name: Desafio PicPay
  datasource:
    url: jdbc:h2:mem:picpay
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springdoc: DEBUG
      springdoc.webmvc.api.OpenApiResource: TRACE